[package]
name = "MFEKmath"
version = "0.1.0"
authors = ["Matthew Blanchard <matthewrblanchard@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skia-safe = { version = "0", optional = true }
flo_curves = { git = "https://github.com/MFEK/flo_curves", branch = "master" }
xmltree = "0.10"

# Our modules
glifparser = { git = "https://github.com/MFEK/glifparser.rlib", branch = "master", default-features = false }
#glifparser = { path = "../glifparser.rlib" } # for development

[features]
default = ["skia-safe", "glifparser/skia", "glifparser/mfek"]
