[package]
name = "MFEKmath"
version = "0.1.0"
authors = ["Matthew Blanchard <matthewrblanchard@gmail.com>", "Fredrick R. Brennan <copypasteⒶkittens.ph>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
skia-safe = { version = "*", optional = true }
flo_curves = "0.6"
kurbo = "0.8"
#flo_curves = { path = "../flo_curves" } # for development
xmltree = "0.10"
plist = "1.3"
log = "0.4"
#itertools = "0.10"

# Our modules
glifparser = { git = "https://github.com/MFEK/glifparser.rlib", branch = "master", default-features = false }
#glifparser = { path = "../glifparser.rlib" } # for development

[features]
default = ["glifparser/mfek"]
strict = []
skia = ["skia-safe", "glifparser/skia"]
